/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/LPSP_MedicalFrigate.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.LowPolyColours} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.LowPolyGlow} />
    </group>
  )
}

useGLTF.preload('/LPSP_MedicalFrigate.gltf')
