/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/netflix.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.007']} scale={5} />
      <group position={[-1.9, 1.49, 0]} scale={[2.04, 1, 1.8]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.001']} scale={[2.2, 1, 1.8]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.002']} scale={[2.2, 1, 1.8]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.002']} position={[0, 0, -0.7]} scale={[2.2, 1, 1.8]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.006']} position={[-2.46, 0.93, 0.55]} scale={[0.85, 1, 1]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.006']} position={[-2.46, 0.93, 0.55]} scale={[0.85, 1, 1]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.001']} position={[-0.02, 0.91, -0.13]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.005']} position={[-1.17, 1.05, -1.8]} rotation={[Math.PI / 2, 0, 0]} scale={[0.94, 1, 0.94]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.003']} position={[0, 2.3, 0]} scale={[2.39, 1.17, 2.11]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.003']} position={[0, 2.78, 0]} scale={1.39} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.011']} position={[-1.93, 1.92, 2.22]} scale={[0.43, 1.28, 0.19]} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['Material.010']} position={[-1.71, 3.92, -0.08]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.26} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['Material.008']} position={[2.1, 0.55, -0.82]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.66} />
      <mesh geometry={nodes.Netflix_Symbol_Diagonal.geometry} material={materials['SVGMat.001']} />
      <mesh geometry={nodes.Netflix_Symbol_Diagonal001.geometry} material={materials['SVGMat.003']} />
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.004']} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.004']} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.004']} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.004']} />
      <mesh geometry={nodes.Curve004.geometry} material={materials['SVGMat.004']} />
      <mesh geometry={nodes.Netflix_Symbol_Diagonal002.geometry} material={materials['SVGMat.004']} />
    </group>
  )
}

useGLTF.preload('/netflix.glb')
